### PR TITLE
Added docker-sync integration files and updated the README

### PR DESCRIPTION
**Pull request by cesarb1392**
@paales I hope it can help you!

### CODE REVIEW

**Comment by NickdeK** [comment]
Run into a few issues to get this working for testing
- Couldn't install docker-sync with supplied commands due to to insufficient rights, actually needed `gem install --user-install docker-sync` 
- ```Fatal error: Fatal error during unmarshaling (input_value: ill-formed message),
possibly because client and server have been compiled with different versions of the OCaml compiler.``` when running docker-sync, no files are being synced
- Unsure what user specific settings should be entered in `docker-sync.yml` (might be the cause of above error)

My other issues with syncing:
- We have had a lot of issues in the past with syncing and Magento. From experience I remember that we had a lot of mismatched syncing issues where manual interference was necessary to select the right file to save.
- Would be nice if the syncing command could be included in `docker-compose` somehow.

**Comment by paales** [comment]
### Startup with docker-sync:
Schermafbeelding 2020-06-02 om 17 18 29

### Startup with mutagen:
Schermafbeelding 2020-06-02 om 17 28 35

In my example container I need to transfer 9GB of data from the box to the container. This takes a long time and lots of CPU, the whole system slows down to a crawl.

We are currently syncing because nginx needs to serve a few javascript/css or image files.. We aren't syncing because we need blazing fast disk access. Because of this we can actually move to a network-only system that doesn't sync anything.

### Startup with NFS:
Schermafbeelding 2020-06-02 om 20 16 46

- NFS is pretty fast, more than fast enough for serving the static assets
- NFS doesn't duplicate the disk space
- NFS is native on OSX
- NFS is supported in Docker

We don't need any additional tools to actually use it.

**Comment by zetxek** [comment]
Might be a bit offtopic (or side topic), but related with the ease of setup of NFS: what would be a good guide to set NFS up?

Since Docker Enterprise has been bought it seems that some links don't work (such as [the one in the README](https://github.com/ho-nl/docker-development-box/blob/master/README.md#reasoning)).

Using Google's cache I can get to:
https://webcache.googleusercontent.com/search?q=cache:WkznWBeWbjYJ:https://docs.docker.com/ee/dtr/admin/configure/external-storage/nfs/+&cd=1&hl=en&ct=clnk&gl=nl&client=firefox-b-d

And the docker NFS page redirects now to https://docs.mirantis.com/docker-enterprise/v3.0/dockeree-products/dtr.html, but there's no mention to NFS in that page, only DTR. It's a bit confusing.

**Comment by paales** [comment]
@cesarb1392 @zetxek I've implemented the nfs integration for the nginx container which should solve the sync issues. I'm closing this issue. If the sync issues aren't solved with this we'll reevaluate.

**Comment by zetxek** [comment]
Great @paales  - in the end if the performance is good, and there's less software to install... it's better!

**Pull request closed without merging**
